### ISSUE TITLE
Errors in readme

### ISSUE THREAD

**Issue by Gargo** [quan118/RSSKit#7]
Man, update your readme please because otherwise it is necessary to guess what have you mentioned above

**Comment by quan118** [comment]
Hi @Gargo, thanks for your comment.
Could you be more specific ?

**Comment by Gargo** [comment]
let feedURL:NSURL = NSURL(string:"http://images.apple.com/main/rss/hotnews/hotnews.rss")
let feedParser:FeedParser = RSSFeedParser(feedURL:url)

I'm new in swift programming. It seems other code is workable but xcode require to chage these strings to:
let url:NSURL = NSURL(string:"http://images.apple.com/main/rss/hotnews/hotnews.rss")!
let feedParser:RSSFeedParser = RSSFeedParser(feedURL:url)

**Comment by quan118** [comment]
Thanks @Gargo. Fixed in the latest codebase: 8904c92783eb5db87d027c164daacc3cf33e7715
